### PR TITLE
Testing fix

### PR DESCRIPTION
**Pull request by janash**
Our current test system depends on pinning the chromedriver binary version in the `devtools/conda-envs/test_env.yaml` file to match the stable release on Travis. Unfortunately that means when the `stable` version of Google Chrome is updated on Travis, our tests will fail. This could be fixed by manually changing the pinned version every time.

This PR adds commands to the travis workflow which checks for the google chrome version and installs `chromedriver-binary` based on that output.

### CODE REVIEW

**Comment by janash** [comment]
> Should we remove chromedriver from the environment yml file so we don't have to uninstall first????

We could definitely do that! I didn't know if maybe we want to keep it for someone creating the testing environment locally (otherwise we'll just have to tell them to install chromedriver-binary). Maybe could be incorporated into the `makefile`.

**Comment by paulsaxe** [comment]
Yep, I think I would need to incorporate the same test in the Makefile, because the same problem will happen locally — and probably people will have all sorts of versions of Chrome installed, so it will be worse.

Paul

3793 Fairway View Drive
Riner VA 24149-2247
USA
paul@thesaxes.net
+1.505.603.8182

**Comment by janash** [comment]
Okay, I can add a makefile fix to this PR as well.

**Comment by janash** [comment]
Actually, I'm not sure of how to do that at the moment. I'm going to merge this PR and fix the makefile later.

**Comment by paulsaxe** [comment]
I can fix the Makefile … fairly fluent with them by now.


Paul

3793 Fairway View Drive
Riner VA 24149-2247
USA
paul@thesaxes.net
+1.505.603.8182

**Pull request merged**
